### ISSUE TITLE
Pam doesn't drive the bus on Spring 25

### ISSUE THREAD

**Issue by rcpd** [Zamiell/stardew-valley#11]
Hi just wanted to make a small note that Pam has a unique schedule on Spring 25 where she goes to the clinic instead of driving the bus, so in order to buy the Deluxe Speed Gro on Spring 25 you need to ensure you kept at least one Desert Warp Totem on hand for that specific day.

Probably most of the time people will have bought some totems already and haven't noticed but it can basically brick the run (short of a restoring a save) in that scenario.

Thanks for the fantastic guide.

**Comment by Zamiell** [comment]
can you submit a PR?

**Comment by rcpd** [comment]
#12

**Comment by Zamiell** [comment]
thanks for the PR.
note that you should almost never be paying pam 500 gold to take the bus.
the first time that you get to the desert, you should stock up on totems, and you should never take the bus again after that.
maybe there is some exception somewhere, but i can't think of one off the top of my head

**Comment by rcpd** [comment]
It was my first time trying out the route so I was bit slow unlocking the Vault and it was actually my first time going to the Desert on the 25th, I figured that as long as I got there by then I could still salvage it somewhat I just wouldn't be anywhere near your benchmarks, but alas.

The only other potential situation I can think of is if forgetting to buy/restock totems and manage to not have any on the 25th which would already be sub-optimal as you say and probably not very likely, but it's basically a run killer if you weren't backing up saves or are being strict about not save scumming so I figured it'd be worth the one liner to potentially save someone else from that pain heh.

**Comment by Zamiell** [comment]
>  it's basically a run killer if you weren't backing up saves or are being strict about not save scumming so I figured it'd be worth the one liner to potentially save someone else from that pain heh.

sgtm :)
