### ISSUE TITLE
Minor Timing Clarifications (Spring 15 & Early CC)

### ISSUE THREAD

**Issue by rcpd** [Zamiell/stardew-valley#13]
Hi again,

To hit the Spring 15 timing for doing the initial CC bundles & minecarts it appears to assume one of your mixed seeds was a Cauliflower on Spring 1? Otherwise it would be Spring 17 if not planting a Cauliflower until Spring 5 as per the route. There is a fairly high chance this will happen in most runs (~33% per seed) but it did not happen in my run and that is probably the only reason I caught it. It doesn't really change the route other than slightly delaying what day you go to CC for first time but I feel like this point should be made as one of the preferred/optimal Day 1 outcomes for earlier Minecarts (and therefore a solid chunk of extra mining time etc).

In the Early CC section (and in the original issue bringing it up) I think they may have forgotten to account for Agriculturalist which takes a full day off each of the Pumpkin & Winter Seeds timings, bringing the earliest possible CC completion to Fall 14 instead of Fall 16 for a 15 day difference compared to waiting for Winter 1.

Happy to submit a PR just wanted to check if I was missing anything and of course happy to be corrected if so.

**Comment by Zamiell** [comment]
i think you would have to be insanely lucky to not get a cauli in like the mixed seeds that the guide plants on day 1

but sure, you can submit a pr
