### ISSUE TITLE
Green Bean for Spring Crops bundle

### ISSUE THREAD

**Issue by hawstom** [Zamiell/stardew-valley#15]
Green Bean is not mentioned. Specifically, at the visit to Pierre on Spring 1, buying the Green Bean Starter is not mentioned, and at the end of Spring 1 where it says the following, it does not mention purchased Green Bean Starter.

"If one of the mixed seeds is not a Cauliflower (check with a mod or the wiki) you'll need to delay handing in the initial bundles and shipping any additional gold for the vault originally scheduled for Spring 15 until Spring 17."

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by hawstom** [comment]
Done.
