### ISSUE TITLE
Crows

### ISSUE THREAD

**Issue by hawstom** [Zamiell/stardew-valley#17]
It's apparent, but not explained, that the route doesn't avoid Crows (Spring Crops bundle delay) by limiting the number of crops to 15 on Spring 1. I don't know the reason why it doesn't. I would add an explanation in a pull request if you can point me to the explanation. Otherwise, can you add it at Min-Max_Guide.md:325?

**Comment by Zamiell** [comment]
you can submit a pull request
iirc the reason is because it is more valuable to plant 5-10 mixed seeds than it is for a crow to potentially eat a parsnip
(crows will never eat crops planted by mixed seeds)
feel free to double check the math on this

**Comment by hawstom** [comment]
I think that if "crows will never eat crops planted by mixed seeds", that is the explanation I will add. But do you have a reference for that? The closest I can find is this, and it's not there: https://stardewvalleywiki.com/Animals#Crows

**Comment by Zamiell** [comment]
actually I misspoke, a crow can eat seed as long as it is not a foraging-related seed (Spring Seeds, Summer Seeds, etc.)
so the reason is that "it is more valuable to plant 5-10 mixed seeds than it is for a crow to potentially eat one of your crops"
