### ISSUE TITLE
Catfish for klutzes

### ISSUE THREAD

**Issue by hawstom** [Zamiell/stardew-valley#23]
It's apparent that this guide is for mere humans even though it is a tight route.
It's also apparent that this guide is trying really hard to leverage forest river catfish on rainy Spring 3.
There is a compounding problem for a player who not getting to Fishing 4 on Spring 2. 1) They are in the lower rankings of player ability to catch fish, and 2) they are attempting Catfish with inadequate farmer proficiency.
So I will go ahead and ask this question about what is deemed optimal for Catfish fishing before I try to address klutzes possibly around Min-Max_Guide.md:380.

1. Is the guide officially recommending that the mere human player probably will not get the advantage of the available Catfish if they are not at Fishing level 4?
2. If a player cannot or does not get to Fishing level 4 on Spring 2, should the guide warn that failure to reach fishing 4 on Spring 2 doesn't foreshadow a profitable day of Catfish fishing, and that they should consider fishing at the beach (or are short casts at the river a viable strategy?) until they reach level 4 and can afford Trout Soup?

Tom

**Comment by Zamiell** [comment]
> Is the guide officially recommending that the mere human player probably will not get the advantage of the available Catfish if they are not at Fishing level 4?

Without having done extension testing, and purely based on memory, it seems like:
1) You can probably catch around 50% of catfishes at level 3.
2) You can probably catch around 75% of catfishes at level 4.

So yes, I think it is still objectively worth it to go for catfishes, even if you only catch 50% of them.

This is an empirical question. So if we assume a 50% catch rate, we can actually just pump the numbers into a spreadsheet and find out, right? (You would probably want to go on a practice file and see if the 50% number is even accurate first, but I guess the number also depends on how good you are at the fishing game.)

> If a player cannot or does not get to Fishing level 4 on Spring 2, should the guide warn that failure to reach fishing 4 on Spring 2 doesn't foreshadow a profitable day of Catfish fishing, and that they should consider fishing at the beach (or are short casts at the river a viable strategy?) until they reach level 4 and can afford Trout Soup?

Trout Soup could be worth it, but it is kind of expensive, and doesn't last very long.

As for fishing on the beach, that entirely depends - what is the gold-per-hour for rainy beach? What is the gold-per-hour for rainy mountain lake? I haven't calculated that myself. Building on what I said above, you would need to calculate that, it seems like a purely empirical question that can be answered given some basic assumptions about catfish-miss rate.

**Comment by Zamiell** [comment]
more thoughts:

in particular, appendix C should probably be moved into a Google spreadsheet.
that would make it easier to add other sections (like e.g. rainy beach), and reduce the chance of typos messing up the calculations.
if you want to create one and give me edit access, then I'll delete all the text in appendix C and link to the new spreadsheet instead.

**Comment by hawstom** [comment]
Can you go to this spreadsheet and request edit access? There is a Fish Income sheet there, but I think it's best to add another sheet, so I did. If you think they can live together in the same sheet, feel free. But I think it will be easier for your creative juices to be in an empty sandbox.

https://docs.google.com/spreadsheets/d/1Hd7M6ITTDcdGbqGiTtgrp0vgXuJqLaCP2xJ3LaV8gbU/edit#gid=55943689

**Comment by hawstom** [comment]
Also, I did some testing, and here's my conclusion for a player with my level of "all-thumbs-ness":

1. You really need to have around 1200 gp on the morning of Spring 2. Otherwise you aren't likely to get a Fiberglass Rod and bait.
2. It's okay if you don't make Fishing 4 on Spring 2. Go to the river on Spring 3 anyway as soon as you have plenty of bait as the guide says. You can still catch some Catfish, and you will level up quickly. Take Trout Soup with you if you feel like you need it, but go to the River.
3. It's okay if you are a day or a level behind the guide fishing levels for a while. The fish money still comes in quickly.

**Comment by Zamiell** [comment]
> You really need to have around 1200 gp on the morning of Spring 2. Otherwise you aren't likely to get a Fiberglass Rod and bait.

it should be pretty easy to get that much i think

> Whether you maximize that with the reward for meeting everybody and giving your first gift or clearing 100 more weeds on your farm, maximize it.

since each fiber sells for 1g, and the drop rate is 50%, you would have to kill 200 weeds to make up for losing 100g.
have you experimented with that? is it reliably better on average?
tangent: on the beach farm, i am able to talk to every NPC and also kill every weed on the farm anyway

**Comment by hawstom** [comment]
Spring 1: I think I am in line now. I proposed a better wording in one of my pull requests.
Catfish: I think I proposed reassuring wording in a pull request today.
1200 gp: I plan to do some tests so I can address this. But I am hoping it's almost always pretty easy.

**Comment by hawstom** [comment]
I am proposing changes here since they are probably controversial. This is at Spring 2:

- Give the rock to Willy and claim the reward for the "How To Win Friends" quest (100g).
- Place the chest on the south edge of the pier near the east end.
- Check the beach for forageables and any artifact spot you may still need to check for the 250g Museum reward.
  - Retrieve any foragable items + artifact spots.
  - If you get an artifact now and did not get one on Spring 1, then immediately go turn it in and claim the reward (250g).
- Fish with the Bamboo Pole until 9:00 AM facing west from the west edge of the pier. Use maximum casts.
- Go to Willy's shop. Sell all beach foragable items + fish. Buy the [Training Rod](https://stardewvalleywiki.com/Training_Rod) from Willy for 25g.
  - The Training Rod will allow more perfect catches. (Leveling up the fishing skill with perfect catches is more important than getting higher-quality fish.)
  - With the Training Rod, use minimum casts. 
  - Minimum casts gives a greater probability to catch easier fish and also saves time on casting/reeling animations.
  - Also see [General Fishing Strategy](#general-fishing-strategy).
- Fish with the Training Rod anywhere near your chest in any direction until you reach fishing level 2.
  - If it's too late to buy a Fiberglass Rod (past 4:30 PM), you will be diverging from the route and on your own to some extent due to poor fishing skills. Keep fishing with the Training Rod. Tomorrow come straight to the beach and buy the Fiberglass Rod and bait as soon as you can. Go to the forest river only when you are at fishing level 4. Otherwise, follow the route as much as you can.
  - If you don't have enough fish to sell to get up to 1,800g, switch to the Bamboo Pole until you do.
  - When you have enough fish to sell to get up to 1,800g, sell all the fish, and buy the [Fiberglass Rod](https://stardewvalleywiki.com/Fiberglass_Rod) from Willy. Also, buy as much [Bait](https://stardewvalleywiki.com/Bait_(item)) as possible (5g each) and equip it on the new rod. You can now destroy the Training Rod.
- Fish facing east from the pier. Use maximum casts.
- Even though we will have less perfect catches, the Fiberglass Rod will allow us to gain experience faster because of the bait.
- If out of Seaweed (1.54 GPE) and Joja Cola (1.92 GPE), eat the highest quality Anchovy (1.82 GPE) or Herring (1.82 GPE).
- Fish using max casts at the same spot as before.
- At 4:30 PM, if you do not have at least 35 bait on the rod, go to Willy and buy more. (You need enough bait to last for the rest of the day + tomorrow morning.)
- Fish until 2 AM. Before passing out, leave all of the fish in the chest. (We will sell them to Willy tomorrow.)
- At the end of the day, you ideally should get:
  - Fishing 0 --> 4

Notes:
- Why west edge of pier first? Waiting until 8:40 A.M. to go forage the beach is a problem in the event we need to visit the Museum. Fishing from the west end enables us to always go foraging immediately (without any backtracing) after giving the rock to Willy. Then we fish a few fish from the west edge until the Fish Shop opens, after which we go to our chest.
  - Won't we fill our backpack? Unlikely. We are likely to have time for only 2 or 3 fish.
  - Is there room? At fishing 0 and 1, yes there is.
- Why all this? Mainly 
  - to implement your Bamboo Pole swap in suggestion
  - to address poor fishing skills and their divergence from the route

**Comment by Zamiell** [comment]
i edited your post with several updates, next time you should just do a PR so that you can see what i am updating

**Comment by Zamiell** [comment]
> Why west edge of pier first? Waiting until 8:40 A.M. to go forage the beach is a problem in the event we need to visit the Museum.

yes im fine with reordering the forage+artifact run to the beginning of the day
