### ISSUE TITLE
Trash cans

### ISSUE THREAD

**Issue by hawstom** [Zamiell/stardew-valley#26]
The guide is very specific about checking trash cans in the first two days, but then it goes silent. What is the intent for trash checking after Spring 2. I am happy to submit a PR if I know what it is to say? Are we ignoring trash cans once we get the Fiberglass rod? Are we hitting them only as extremely convenient? And what's the purpose of checking trash cans? Income, food, resources, or just general "goodies"?

**Comment by Zamiell** [comment]
Trash Cans have a very low chance of getting anything good. Thus, the expected value of a trash can is extremely low, especially once you are past the first week when you have plenty of energy-restoring chubs and/or infinite Salads.

**Comment by hawstom** [comment]
I can address this now. Thanks.
