### ISSUE TITLE
The Museum, Geodes, and Forage

### ISSUE THREAD

**Issue by hawstom** [Zamiell/stardew-valley#27]
I may have missed it, but the guide seems not to give a general approach for Museum donations other than the first artifact. Is there a general recommendation between selling and donating. Same with Geodes and Forage (sell vs plant or gift).

**Comment by Zamiell** [comment]
That entirely depends on what your challenge run is. For example, if you are doing a 5 candles run, then you should wait until Year 1 Fall, if you are doing some kind of 2-year challenge, then you should defer it until Year 2 after Ginger Island stuff.

**Comment by Zamiell** [comment]
All geodes / frozen geodes / magma geodes/ etc. should almost certainly be sold for the extra cash early on. You will have tons of Omni Geodes later on from 10+ hours of Skull Caverns farming, with which you can use to get all of the minerals. If you are doing a 2-year hat challenge, maybe this changes the calculus a bit, but that's probably not worth mentioning.

**Comment by hawstom** [comment]
Thanks. I can address the geodes with one other clarification. Shipped directly or crushed and sold?

**Comment by Zamiell** [comment]
you ship them directly, any time spend walking to the blacksmith is wasted fishing profit

**Comment by hawstom** [comment]
1. On further examination and reflection, I think that a word of introduction is needed about

- Community Center
  - In this route, we are only rushing the ____ bundles/rooms. Ship everything else for income until ____.
- Museum
 - In this route, we are not rushing anything but the first donation. Ship all other artifacts and gems until _____. 
- Geodes
 - Ship all geodes for simplicity until ____.
- Friendship
  - This is covered well in the Preface.Friendship section. Defer friendship until later including birthdays. 

2. I don't know where these should go.

- Together in a single Preface.Saving section or What to save section? 
- In individual Preface sections?
- Under some date?

**Comment by Zamiell** [comment]
I added this to the goals section:

```
In order to maximize money, this route completely ignores friendship with NPCs, filling the museum, and completing the community center (outside of what is explicitly required to open the Skull Caverns). All of that stuff can wait until much later on in the run when you have a huge economy going.
```

**Comment by Zamiell** [comment]
does anything beyond that need to be mentioned?

**Comment by hawstom** [comment]
I like that. 

Is there a place to mention "Ship instead of crushing all geodes for simplicity"? Maybe here?

"...friendship with NPCs, filling the museum (for simplicity, we ship all geodes instead of crushing them), and completing..."

**Comment by Zamiell** [comment]
>Is there a place to mention "Ship instead of crushing all geodes for simplicity"?

hrm, i dont know, i am open to suggestions

> Maybe here? "...friendship with NPCs, filling the museum 

probably not, to be honest, its too specific, and probably belongs somewhere else.
when do you get your first geode? on spring 5 when you go mining for the first time, right?
probably add a bullet point to the Spring 5 section that says:

- In the mines, you will get [Geodes](https://stardewvalleywiki.com/Geode), [Frozen Geodes](https://stardewvalleywiki.com/Frozen_Geode), and [Magma Geodes](https://stardewvalleywiki.com/Magma_Geode). If you do the math, they are technically worth more gold on average if you pay 25g to Clint to break them. However, this does not account for the opportunity cost of having to walk to Clint's blacksmith in the middle of the day to do this, which is a huge drain that dwarfs the marginal increase in value from breaking them. Thus, all types of Geodes should be shipped for the extra cash. (You should hold off on worrying about minerals and completing the museum until the very end of the game.)

**Comment by hawstom** [comment]
I like that. Let's leave this open until done.
