### ISSUE TITLE
convert fishing appendix to google sheets

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/stardew-valley#31]

**Comment by Zamiell** [comment]
wip: https://docs.google.com/spreadsheets/d/1Zv0VCgFyJRlh1kVyvogYZviaqCexrDYhp7GNEQxozBM/edit#gid=0

**Comment by hawstom** [comment]
Should I copy this to "Stardew Valley Community Spreadsheet" "Fishing Hourly Income" once substantially done?

https://docs.google.com/spreadsheets/d/1Hd7M6ITTDcdGbqGiTtgrp0vgXuJqLaCP2xJ3LaV8gbU/edit#gid=55943689

**Comment by Zamiell** [comment]
i'd rather have it on my own spreadsheet than a communal one, but you can link to my spreadsheet from the communal one if you want

**Comment by Zamiell** [comment]
ok, the spreadsheet is done now, and now we can more easily add new areas

**Comment by Zamiell** [comment]
i updated the doc to include a link to the spreadsheet

**Comment by Zamiell** [comment]
i also added mountain lake raining, forest river sunny, and ocean raining
