### ISSUE TITLE
Fishing spreadsheet mistake?

### ISSUE THREAD

**Issue by hawstom** [Zamiell/stardew-valley#35]
I think you made the same mistake I was about to make at Intro!I29. You calculated the average as 

(max - min)/2 = 13450 ms

But it should be

min + (max - min)/2  =  14050 ms
or more classically
(max + min)/2 = 14050 ms

Right?

**Comment by Zamiell** [comment]
yeah i guess so

**Comment by Zamiell** [comment]
for 100-200:

(200 - 100)/2 = 50 ms

(200 + 100)/2 = 150 ms

**Comment by Zamiell** [comment]
ok, it should be fixed on the spreadsheet now.
the good thing about spreadsheets is that i dont have to manually redo any of the calculations, lol
