### ISSUE TITLE
Day 1 and 2

### ISSUE THREAD

**Issue by OfficialOhWen** [Zamiell/stardew-valley#36]
Day one doesn't have a place to meet mayor Lewis, therefor not completing "Introductions" quest talking to willy on day 2, and making the gift quest not complete day 2. Willy also does not sell the fiberglass rod day 2, it now requires a fishing level for him to have in shop

**Comment by Zamiell** [comment]
Was there a patch or something? You automatically meet the mayor in the intro, obviously.
