### ISSUE TITLE
Mining and meeting people

### ISSUE THREAD

**Issue by tted3286** [Zamiell/stardew-valley#37]
Just an imperfection that sticks out like a sore thumb, why is your mining level 0 until day 6.  This is pathetic.  Remember all rocks outside count as xp, and both four corners and hilltop farm have discreet nodes.  ALSO, that is a lot of work, meeting everyone for just 100g, waste of time, better to forage with 100% completion.

Everything else is on point thus far in my read

**Comment by Zamiell** [comment]
you do already forage with 100% completion and meet everyone at the same time
