### ISSUE TITLE
Fiberglass rod can no longer be purchased

### ISSUE THREAD

**Issue by alfaproject** [Zamiell/stardew-valley#47]
Latest patch does not allow buying the rod anymore until we hit level 2, so Spring day 2 is not really feasible as is anymore

**Comment by Zamiell** [comment]
Do you want to submit a pr?

**Comment by alfaproject** [comment]
I'm not sure exactly how to adjust the route to compensate for it ):

**Comment by jacobb** [comment]
How is this a change? It's always been required to be level 2

**Comment by alfaproject** [comment]
So has the guide always been broken or am I missing something? Spring day 2, you have level 0 fishing

**Comment by Zamiell** [comment]
Yeah, but you can go from level 0 --> level 2 when fishing from 8 AM to 3-4 PM ish.
The exact time varies because of bubbles and how skilled you are at fishing.

**Comment by alfaproject** [comment]
But you only level up after sleeping, right?

**Comment by Zamiell** [comment]
no, you level up instantly

**Comment by alfaproject** [comment]
Oh ok, sorry for the noise then, and thanks!
