### ISSUE TITLE
River fishing placement

### ISSUE THREAD

**Issue by LostLogic** [Zamiell/stardew-valley#6]
Hello!
Love the guide, but I'm not sure if I understood the place to fish & place the chest.
Is this the spot? Red X: Player, Purple Square: Chest
![Location](https://user-images.githubusercontent.com/7568950/117187171-ee286580-addb-11eb-96cb-41f948f13a69.png)

**Comment by Zamiell** [comment]
yes, that's correct, i've never had it destroyed /shrug

**Comment by LostLogic** [comment]
Cool! Wanted to know before I tried a run. Thanks!

**Comment by Zamiell** [comment]
np
