### ISSUE TITLE
Broken/ outdated link

### ISSUE THREAD

**Issue by AmitSrourDev** [Zamiell/stardew-valley#8]
I'm following the guide and I stumbled upon a link that is unavailable:
["lowest gold per energy ratio"](https://stardewvalleywiki.com/User:Zamiel/Gold_to_Energy_Ratios)
under [https://github.com/Zamiell/stardew-valley/blob/master/Min-Max_Guide.md#gold-per-energy-list-gpe](https://github.com/Zamiell/stardew-valley/blob/master/Min-Max_Guide.md#gold-per-energy-list-gpe)

**Comment by Zamiell** [comment]
fixed
