### ISSUE TITLE
Min/Max wheat issue/question

### ISSUE THREAD

**Issue by scssquatch** [Zamiell/stardew-valley#9]
Just wanted to point out in your guide you say wheat seeds are 5g each but they're 10g each.

Also I think it'd be helpful to put a note near the end of summer to put in the sprinklers and hoe the extra area because it's impossible to harvest the starfruit, buy the seeds, hoe an extra like 800+ tiles, add speed-gro and plant the wheat seeds in the same day. If you hoe and put sprinklers you can offload some of that into an earlier day. Just would be nice for dumb people like me to have a heads up it's a ton of stuff to do. This is also relevant because if the tiles aren't already watered from before you need to water them too to get them in 2 days.

**Comment by Zamiell** [comment]
can you submit a PR?

**Comment by scssquatch** [comment]
#10
